# Generated by Django 4.1 on 2022-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_aws_access_key',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='user_aws_secret_key',
            field=models.TextField(default=None),
        ),
    ]
