# Generated by Django 4.1.1 on 2022-09-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_user_aws_access_key_user_user_aws_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_aws_access_key',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_aws_secret_key',
            field=models.TextField(default=None, null=True),
        ),
    ]
