version: '3'

volumes:
  prometheus-data:
    driver: local
  db-data:
    driver: local

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432/tcp"
    volumes:
      - db-data:/var/lib/db-data
    mem_reservation: 512m
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: cloud


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./ciso_back_end/conf/prometheus:/conf/prometheus
      - prometheus-data:/prometheus
    mem_reservation: 512m
    restart: unless-stopped
    command:
      - "--config.file=/conf/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=30d"