global:
  scrape_interval: 15s 


# A scrape configuration containing exactly one endpoint to scrape:

scrape_configs:

  - job_name: 'EC2-Instances'
    http_sd_configs:
      - url: 'http://host.docker.internal:8000/api/dashboard/prometheus-targets/'
        refresh_interval: 10s

