# Generated by Django 4.0.3 on 2022-04-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=100, unique=True)),
                ('ipv4', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
