# Generated by Django 4.0.3 on 2022-04-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='id',
            new_name='Instanceid',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='ipv4',
            new_name='Instanceipv4',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='name',
            new_name='Instancename',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='status',
            new_name='Instancestatus',
        ),
    ]
