# Generated by Django 4.0.3 on 2022-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_id_instance_instanceid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='InstanceAWSAccessKey',
            field=models.TextField(default='Unknown', unique=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='InstanceAWSSecretKey',
            field=models.TextField(default='Unknown', unique=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='Instancestatus',
            field=models.CharField(default='Unknown', max_length=100, null=True, unique=True),
        ),
    ]
