# Generated by Django 4.0.3 on 2022-04-25 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_instance_instanceawsaccesskey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instance',
            old_name='InstanceAWSAccessKey',
            new_name='instance_AWSAccessKey',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='InstanceAWSSecretKey',
            new_name='instance_AWSSecretKey',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='Instanceid',
            new_name='instance_id',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='Instanceipv4',
            new_name='instance_ipv4',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='Instancename',
            new_name='instance_name',
        ),
        migrations.RenameField(
            model_name='instance',
            old_name='Instancestatus',
            new_name='instance_status',
        ),
    ]
