# Generated by Django 4.0.3 on 2022-04-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_rename_instanceawsaccesskey_instance_instance_awsaccesskey_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='instance_status',
            field=models.CharField(default='Unknown', max_length=100, null=True),
        ),
    ]
