# Generated by Django 4.0.4 on 2022-05-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_instance_instance_awsaccesskey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='instance_AWSSessionToken',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_os',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_pricing_plan',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_region',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='instance_volume_type',
            field=models.TextField(null=True),
        ),
    ]
