# Generated by Django 4.1 on 2022-08-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('instance_id', models.AutoField(primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=100, unique=True)),
                ('instance_status', models.CharField(default='Unknown', max_length=100, null=True)),
                ('instance_ipv4', models.CharField(max_length=100, unique=True)),
                ('instance_aws_secret_key', models.TextField(unique=True)),
                ('instance_aws_access_key', models.TextField(unique=True)),
                ('instance_region', models.TextField()),
                ('instance_os', models.TextField(null=True)),
                ('instance_volume_type', models.TextField(null=True)),
                ('instance_type', models.TextField(null=True)),
                ('instance_pricing_plan', models.TextField(null=True)),
            ],
        ),
    ]
