# Generated by Django 4.1 on 2022-09-21 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_password'),
        ('instances', '0002_alter_instances_instance_aws_access_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instances',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
