# Generated by Django 4.0.3 on 2022-05-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_username', models.CharField(max_length=100)),
                ('user_firstname', models.CharField(max_length=100)),
                ('user_lastname', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=100)),
            ],
        ),
    ]
